### ISSUE TITLE
pkg-config fails to find cairo.pc and glib-2.0.pc on MSYS2 Win64

### ISSUE THREAD

**Issue by Tenebryo** [alexcrichton/pkg-config-rs#23] opened 2016-03-25 05:57 UTC
I am trying to build a simple GTK test app on Win64 (using MSYS). When I try to build it, the following happens:

```
Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ cargo build
   Compiling glib-sys v0.3.0
   Compiling cairo-sys-rs v0.3.0
Build failed, waiting for other jobs to finish...
failed to run custom build command for `cairo-sys-rs v0.3.0`
Process didn't exit successfully: `D:\dev\Rust\src\gtk_test\target\debug\build\cairo-sys-rs-45a32580d0558aa8\build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "cairo >= 1.10"` did not exit successfully: exit code: 1
--- stdout
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
```

I noticed that pkg-config was failing to find either `cairo.pc` or `glib-2.0.pc`. I found the files it was missing in the $PKG_CONFIG_PATH, so I tried running the same pkg-config call it says it is running, and it seems to run fine without errors.

```
Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ echo $PKG_CONFIG_PATH
/usr/lib/pkgconfig:/usr/share/pkgconfig:/lib/pkgconfig:/mingw64/lib/pkgconfig

Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ find /mingw64 -name cairo.pc
/mingw64/lib/pkgconfig/cairo.pc

Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ find /mingw64 -name glib-2.0.pc
/mingw64/lib/pkgconfig/glib-2.0.pc

Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ pkg-config --libs --cflags "cairo >= 1.10"
-mms-bitfields -I/mingw64/include/cairo -I/mingw64/include/pixman-1 -I/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -I/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -I/mingw64/include/libpng16 -L/mingw64/lib -LC:/building/msys64/mingw64/lib/../lib -L/mingw64/lib -lcairo -lz -lgobject-2.0 -lffi -lpixman-1 -lfontconfig -lexpat -lfreetype -liconv -lexpat -lfreetype -lz -lbz2 -lharfbuzz -lglib-2.0 -lintl -pthread -lws2_32 -lole32 -lwinmm -lshlwapi -lintl -lpng16 -lz
```

I'm not sure if I am doing something wrong or not, but I've been fiddling around with settings and Googling solutions for a while to no avail.

**Comment by alexcrichton** [comment] 2016-03-25 15:54
Hm I wonder if perhaps `$PKG_CONFIG_PATH` was different at build time and in the shell? I don't think this does anything strange with respect to paths...

**Comment by Tenebryo** [comment] 2016-03-26 00:19
I don't think `$PKG_CONFIG_PATH` was different - it is set in `.bash_profile`. I tried `cargo build` and the corresponding `pkg-config` call again just to make sure, and I get the same error with `cargo build` while the plain `pkg-config` still works.
```
Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ echo $PKG_CONFIG_PATH
/usr/lib/pkgconfig:/usr/share/pkgconfig:/lib/pkgconfig:/mingw64/lib/pkgconfig

Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ cargo build
   Compiling cairo-sys-rs v0.3.0
   Compiling glib-sys v0.3.0
Build failed, waiting for other jobs to finish...
failed to run custom build command for `cairo-sys-rs v0.3.0`
Process didn't exit successfully: `D:\dev\Rust\src\gtk_test\target\debug\build\cairo-sys-rs-45a32580d0558aa8\build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "cairo >= 1.10"` did not exit successfully: exit code: 1
--- stdout
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found

Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ pkg-config --libs --cflags "glib-2.0 >= 2.32"
-mms-bitfields -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -L/mingw64/lib -lglib-2.0 -lintl -pthread -lws2_32 -lole32 -lwinmm -lshlwapi -lintl

Sam@sam-laptop MSYS /d/dev/Rust/src/gtk_test
$ pkg-config --libs --cflags "cairo >= 1.10"
-mms-bitfields -I/mingw64/include/cairo -I/mingw64/include/pixman-1 -I/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -I/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -I/mingw64/include/libpng16 -L/mingw64/lib -LC:/building/msys64/mingw64/lib/../lib -L/mingw64/lib -lcairo -lz -lgobject-2.0 -lffi -lpixman-1 -lfontconfig -lexpat -lfreetype -liconv -lexpat -lfreetype -lz -lbz2 -lharfbuzz -lglib-2.0 -lintl -pthread -lws2_32 -lole32 -lwinmm -lshlwapi -lintl -lpng16 -lz
```

**Comment by alexcrichton** [comment] 2016-03-28 05:55
Hm can you try building a Rust program that just does something like:

```rust
Command::new("pkg-config").arg("--libs").arg("--cflags").arg("cairo >= 1.10").status();
```

and see what happens? If that works I'd be surprised, but may help isolate the problem.

**Comment by gkoz** [comment] 2016-04-02 14:34
@Tenebryo you can use [procmon](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) to find out where exactly `pkg-config` is looking for the `.pc` files.

**Comment by mitaa** [comment] 2016-06-28 18:57
```
$ echo $PKG_CONFIG_PATH
/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
```

Thanks for the pointer @gkoz, it seems like pkg-config looks only within `/mingw64/share/pkgconfig`
Changing the order of the two `$PKG_CONFIG_PATH` entries "fixes" the immediate problem for me.

```
PKG_CONFIG_PATH=/mingw64/share/pkgconfig:/mingw64/lib/pkgconfig
```

**Comment by henninglive** [comment] 2016-08-12 20:58
Duplicate of #12, fixed by installing `mingw-w64-x86_64-pkg-config` or `mingw-w64-i686-pkg-config` instead of `pkg-config`.

**Comment by alexcrichton** [comment] 2017-01-24 17:30
Sounds like this wasn't a bug with this crate, so closing.

**Closed by alexcrichton** 2017-01-24 17:30 UTC
